### ISSUE TITLE
Set up initial Django project for deployment using Docker

### ISSUE THREAD

**Issue by jonc125** [UCL/SUMMIT-blood-samples#1]
I suggest following https://cookiecutter-django.readthedocs.io/en/latest/deployment-with-docker.html unless you have a better idea.

The virtual machine OS will be RHEL7.

Project [settings](https://cookiecutter-django.readthedocs.io/en/latest/project-generation-options.html) agreed with @johnmccabe44:
- project_name = summit_blood_samples
- domain_name = summitbloodsamples.rc.ucl.ac.uk
- source code licence = BSD

For other options, I would suggest:
- use_pycharm on
- use_docker on
- use_heroku and use_sentry off
- latest postgres
- no cloud provider or mail service (we can use UCL's SMTP server once deployed; you will probably need to attach a postfix container to the docker-compose setup for dev purposes, or maybe use MailHog, I don't have experience with that)
- Travis for CI

I don't have strong opinions on the rest!

**Comment by nels** [comment]
able to deploy with
`$ docker-compose -f local.yml up --build`

doing so with _production.yml_ requires further configuration for TLS & reverse proxy
