### ISSUE TITLE
Password reset email has wrong link

### ISSUE THREAD

**Issue by jonc125** [UCL/SUMMIT-blood-samples#11]
All the URLs, including the important reset link, go to https://127.0.0.1:8000 rather than the production server URL. I can't spot where this is configured.

Incidentally, is an email supposed to be sent when a user is created via the admin interface? This didn't happen for me; I only received an email when using the 'forgot my password' link.

**Comment by saikrishnanooka-vl** [comment]
@jonc125 we need to update the fixtures.json file with production domain URL below 
```
{
        "model": "sites.site",
        "pk": 1,
        "fields": {
            "domain": "127.0.0.1:8000",
            "name": "Blood Sample Site"
        }
    }
```

[Initial Data Setup in Readme file](https://github.com/UCL/SUMMIT-blood-samples#initial-data)

**Comment by jonc125** [comment]
I used the -production version of the fixtures, so it does have the correct URL. And in the Django shell I can do
```
>>> django.contrib.sites.models.Site.objects.all()
<QuerySet [<Site: summitbloodsamples.rc.ucl.ac.uk>]>
```
So the correct site info is in the database. But it doesn't appear to be used. Probably the context for the email templates is not being set up correctly? I _think_ you're using the built-in `django.contrib.auth.views` for this, just configured in `config/urls.py`?

**Comment by jonc125** [comment]
Ah, I spoke too soon. It seems that Django was caching an old value; re-creating the container has got it working now. I'll update the readme to reflect that a restart is needed after installing the fixture.

**Comment by saikrishnanooka-vl** [comment]
Thanks @jonc125 for confirming

**Comment by saikrishnanooka-vl** [comment]
@jonc125 We also need to update the mail configuration in base.py settings to UCL email.

Let me know if you need any help in this

**Comment by jonc125** [comment]
That part is done, but in production.py which the deployment here uses.
